### ISSUE TITLE
error when I run conda env create -f environment.yml

### ISSUE THREAD

**Issue by valadad** [AmmarKamoona/RFS-Energy-Anomaly-Detection-of-Defect#1]
Hi

There is error when I run `conda env create -f environment.yml`

![image](https://user-images.githubusercontent.com/56509851/131423752-df1bbb53-469d-4044-989a-ec10f5dbc49e.png)

**Comment by AmmarKamoona** [comment]
Hi @valadad  
I have updated the environment.yml  file again and tested on different machine. Please redownload the new file named as rfs.yml.

**Comment by valadad** [comment]
Hi 

same error

**Comment by AmmarKamoona** [comment]
Hi there, 
Another option is to install packages separately one by one. 
Starting by creating the virtual environment
#
conda create --name rfs python=3.6
conda activate rfs
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
#
Then, install the other dependencies
